# じゃらんデータ整備のためにサンプルデータを作る

## データの読み込み

In [21]:
import csv
# csv_file出力
import os
import pandas as pd
# Shift-JIS 形式の CSV ファイル (employee.sjis.csv) して出力
# df.to_csv("employee.sjis.csv", encoding="shift_jis")
# csvを開く。

os.chdir("D:\じゃらん宿泊データ\original_data")

csv_file_name = "hotel_res2021-04-01.csv"
columns = ["エリアコード","宿コード","データ取得日","チェックイン日","プランコード","価格","部屋情報","朝食の有無","夕食の有無","チェックイン時刻","チェックアウト時刻","プラン提供開始日","プラン提供終了日","イメージ画像URL","画像キャプション","残り部屋数"]

df = pd.read_csv(csv_file_name,names=(columns))
df.head()

,エリアコード,宿コード,データ取得日,チェックイン日,プランコード,価格,部屋情報,朝食の有無,夕食の有無,チェックイン時刻,チェックアウト時刻,プラン提供開始日,プラン提供終了日,イメージ画像URL,画像キャプション,残り部屋数
0,10202,300206,2021-04-01,2021-04-01,630738,3600,【1名利用】ダブルorツインルーム 2020年2月リニューアル済,0,0,15:00,11:00,20080916,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ダブルルーム ベッド幅140cm,NaN
1,10202,300206,2021-04-01,2021-04-01,630738,3700,禁煙ダブルルーム 2020年客室リニューアル完了（15～17平米）,0,0,15:00,11:00,20111118,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ダブルルーム ベッド幅140cm,NaN
2,10202,300206,2021-04-01,2021-04-01,630738,4100,禁煙ツインルーム 2020年客室リニューアル完了（18平米）,0,0,15:00,11:00,20080916,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ツインルーム ベッド幅120cm,6.0
3,10202,302905,2021-04-01,2021-04-01,3102459,8000,リニューアルフロア・ツイン/アーバン＜２３平米＞,0,0,15:00,11:00,20210220,20210531,https://www.jalan.net/jalan/images/pictM/Y5/Y3...,期間限定＆室数限定のお得なプラン♪,2.0
4,10202,302905,2021-04-01,2021-04-01,3102459,8000,スタンダードフロア・ツイン＜アーバンルーム＞２３平米,0,0,15:00,11:00,20210220,20210531,https://www.jalan.net/jalan/images/pictM/Y5/Y3...,期間限定＆室数限定のお得なプラン♪,2.0

## データを10000行だけ抽出

In [22]:
# df_sample = df.iloc[:10000]
df_sample = df.copy()

## テキストをまとめて元のデータを削除

In [23]:
text = df_sample["部屋情報"] + df_sample["画像キャプション"]
df_s_text = pd.DataFrame(text,columns=["text"])
df_s_text

                                                       text
0          【1名利用】ダブルorツインルーム　2020年2月リニューアル済ダブルルーム　ベッド幅140cm
1         　禁煙ダブルルーム　2020年客室リニューアル完了（15～17平米）ダブルルーム　　ベッド幅...
2          禁煙ツインルーム　2020年客室リニューアル完了（18平米）ツインルーム　　　ベッド幅120cm
3                 リニューアルフロア・ツイン/アーバン＜２３平米＞期間限定＆室数限定のお得なプラン♪
4               スタンダードフロア・ツイン＜アーバンルーム＞２３平米期間限定＆室数限定のお得なプラン♪
...                                                     ...
10134750                                         シングルダブルダブル
10134751                    シングルダブル☆格安レンタカー・レンタルバイクで南大東島満喫☆
10134752                                         シングルダブルダブル
10134753                    シングルダブル☆格安レンタカー・レンタルバイクで南大東島満喫☆
10134754                                         シングルダブルダブル

[10134755 rows x 1 columns]

In [24]:
df_s = df_sample.drop(columns=["部屋情報","イメージ画像URL","画像キャプション"])
df_s = pd.concat([df_s, df_s_text], axis=1)
df_s

,エリアコード,宿コード,データ取得日,チェックイン日,プランコード,価格,朝食の有無,夕食の有無,チェックイン時刻,チェックアウト時刻,プラン提供開始日,プラン提供終了日,残り部屋数,text
0,10202,300206,2021-04-01,2021-04-01,630738,3600,0,0,15:00,11:00,20080916,20220228,NaN,【1名利用】ダブルorツインルーム 2020年2月リニューアル済ダブルルーム ベッド幅140cm
1,10202,300206,2021-04-01,2021-04-01,630738,3700,0,0,15:00,11:00,20111118,20220228,NaN,禁煙ダブルルーム 2020年客室リニューアル完了（15～17平米）ダブルルーム ベッド幅...
2,10202,300206,2021-04-01,2021-04-01,630738,4100,0,0,15:00,11:00,20080916,20220228,6.0,禁煙ツインルーム 2020年客室リニューアル完了（18平米）ツインルーム ベッド幅120cm
3,10202,302905,2021-04-01,2021-04-01,3102459,8000,0,0,15:00,11:00,20210220,20210531,2.0,リニューアルフロア・ツイン/アーバン＜２３平米＞期間限定＆室数限定のお得なプラン♪
4,10202,302905,2021-04-01,2021-04-01,3102459,8000,0,0,15:00,11:00,20210220,20210531,2.0,スタンダードフロア・ツイン＜アーバンルーム＞２３平米期間限定＆室数限定のお得なプラン♪
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10134750,471723,382544,2021-04-01,2021-04-28,2317959,4320,0,0,11:00,10:00,20170612,20210831,5.0,シングルダブルダブル
10134751,471723,382544,2021-04-01,2021-04-29,2369744,4320,0,0,11:30,10:00,20171005,20210831,5.0,シングルダブル☆格安レンタカー・レンタルバイクで南大東島満喫☆
10134752,471723,382544,2021-04-01,2021-04-29,2317959,4320,0,0,11:00,10:00,20170612,20210831,5.0,シングルダブルダブル
10134753,471723,382544,2021-04-01,2021-04-30,2369744,4320,0,0,11:30,10:00,20171005,20210831,3.0,シングルダブル☆格安レンタカー・レンタルバイクで南大東島満喫☆
10134754,471723,382544,2021-04-01,2021-04-30,2317959,4320,0,0,11:00,10:00,20170612,20210831,3.0,シングルダブルダブル

In [7]:
len(df_s)

10000

## フラグの追加

In [17]:
kinnen = []
kitsuen = []
wa = []
yo = []
wayo = []
single = []
semidouble = []
double = []
twin = []
tri = []
omakase = []
renpaku = []

for text in df_s["text"]:
    text = str(text)
    kinnen.append(int("禁煙" in text))
    kitsuen.append(int("喫煙" in text))
    wa.append(int("和室" in text))
    yo_wa = int("和洋室" in text) + int("洋室" in text)
    if yo_wa == 2:
        wayo.append(1)
        yo.append(0)
    elif yo_wa == 1:
        wayo.append(0)
        yo.append(1)
    else:
        wayo.append(0)
        yo.append(0)
    single.append(int("シングル" in text))
    semi_dou = int("セミダブル" in text) + int("ダブル" in text)
    if semi_dou == 2:
        semidouble.append(1)
        double.append(0)
    elif semi_dou == 1:
        semidouble.append(0)
        double.append(1)
    else:
        semidouble.append(0)
        double.append(0)        
    twin.append(int("ツイン" in text))
    tri.append(int("トリプル" in text))
    omakase.append(int("おまかせ" in text))
    renpaku.append(int("連泊" in text))

#print(kinnen)
#print(kituen)
df_kinnen = pd.DataFrame(kinnen,columns=["禁煙"])
df_kitsuen = pd.DataFrame(kitsuen,columns=["喫煙"])
df_wa =  pd.DataFrame(wa,columns=["和室"])
df_yo =  pd.DataFrame(yo,columns=["洋室"])
df_wayo =  pd.DataFrame(wayo,columns=["和洋室"])
df_single =  pd.DataFrame(single,columns=["シングル"])
df_semidouble =  pd.DataFrame(semidouble,columns=["セミダブル"])
df_double =  pd.DataFrame(double,columns=["ダブル"])
df_twin =  pd.DataFrame(twin,columns=["ツイン"])
df_tri =  pd.DataFrame(tri,columns=["トリプル"])
df_omakase =  pd.DataFrame(omakase,columns=["おまかせ"])
df_renpaku = pd.DataFrame(renpaku,columns=["連泊"])
df_s = pd.concat([df_s,df_kinnen,df_kitsuen,df_wa,df_yo,df_wayo,df_single,df_semidouble,df_double,df_twin,df_tri,df_omakase,df_renpaku], axis=1)
df_s = df_s.drop(columns="text")
df_s

,エリアコード,宿コード,データ取得日,チェックイン日,プランコード,価格,朝食の有無,夕食の有無,チェックイン時刻,チェックアウト時刻,...,喫煙,和室,洋室,和洋室,シングル,セミダブル,ダブル,ツイン,トリプル,おまかせ
0,10202,300206,2021-04-01,2021-04-01,630738,3600,0,0,15:00,11:00,...,0,0,0,0,0,0,1,1,0,0
1,10202,300206,2021-04-01,2021-04-01,630738,3700,0,0,15:00,11:00,...,0,0,0,0,0,0,1,0,0,0
2,10202,300206,2021-04-01,2021-04-01,630738,4100,0,0,15:00,11:00,...,0,0,0,0,0,0,0,1,0,0
3,10202,302905,2021-04-01,2021-04-01,3102459,8000,0,0,15:00,11:00,...,0,0,0,0,0,0,0,1,0,0
4,10202,302905,2021-04-01,2021-04-01,3102459,8000,0,0,15:00,11:00,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10134750,471723,382544,2021-04-01,2021-04-28,2317959,4320,0,0,11:00,10:00,...,0,0,0,0,1,0,1,0,0,0
10134751,471723,382544,2021-04-01,2021-04-29,2369744,4320,0,0,11:30,10:00,...,0,0,0,0,1,0,1,0,0,0
10134752,471723,382544,2021-04-01,2021-04-29,2317959,4320,0,0,11:00,10:00,...,0,0,0,0,1,0,1,0,0,0
10134753,471723,382544,2021-04-01,2021-04-30,2369744,4320,0,0,11:30,10:00,...,0,0,0,0,1,0,1,0,0,0
10134754,471723,382544,2021-04-01,2021-04-30,2317959,4320,0,0,11:00,10:00,...,0,0,0,0,1,0,1,0,0,0

In [32]:
# こっちの方が20%速い
import numpy as np

kinnen = []
kitsuen = []
wa = []
yo = []
wayo = []
single = []
semidouble = []
double = []
twin = []
tri = []
omakase = []
renpaku = []

for text in df_s["text"]:
    text = str(text)
    kinnen.append(int("禁煙" in text))
    kitsuen.append(int("喫煙" in text))
    wa.append(int("和室" in text))
    yo_wa = int("和洋室" in text) + int("洋室" in text)
    if yo_wa == 2:
        wayo.append(1)
        yo.append(0)
    elif yo_wa == 1:
        wayo.append(0)
        yo.append(1)
    else:
        wayo.append(0)
        yo.append(0)
    single.append(int("シングル" in text))
    semi_dou = int("セミダブル" in text) + int("ダブル" in text)
    if semi_dou == 2:
        semidouble.append(1)
        double.append(0)
    elif semi_dou == 1:
        semidouble.append(0)
        double.append(1)
    else:
        semidouble.append(0)
        double.append(0)        
    twin.append(int("ツイン" in text))
    tri.append(int("トリプル" in text))
    omakase.append(int("おまかせ" in text))
    renpaku.append(int("連泊" in text))
add_list = [kinnen,kitsuen,wa,yo,wayo,single,semidouble,double,twin,tri,omakase,renpaku]
add_list = np.array(add_list).T
df_add = pd.DataFrame(add_list,columns = ["禁煙","喫煙","和室","洋室","和洋室","シングル","セミダブル","ダブル","ツイン","トリプル","おまかせ","連泊"])
# print(kinnen)
# print(kituen)
# df_kinnen = pd.DataFrame(kinnen,columns=["禁煙"])
# df_kitsuen = pd.DataFrame(kitsuen,columns=["喫煙"])
# df_wa =  pd.DataFrame(wa,columns=["和室"])
df_s = pd.concat([df_s,df_add], axis=1)
df_s = df_s.drop(columns="text")
df_s

,エリアコード,宿コード,データ取得日,チェックイン日,プランコード,価格,朝食の有無,夕食の有無,チェックイン時刻,チェックアウト時刻,...,和室,洋室,和洋室,シングル,セミダブル,ダブル,ツイン,トリプル,おまかせ,連泊
0,10202,300206,2021-04-01,2021-04-01,630738,3600,0,0,15:00,11:00,...,0,0,0,0,0,1,1,0,0,0
1,10202,300206,2021-04-01,2021-04-01,630738,3700,0,0,15:00,11:00,...,0,0,0,0,0,1,0,0,0,0
2,10202,300206,2021-04-01,2021-04-01,630738,4100,0,0,15:00,11:00,...,0,0,0,0,0,0,1,0,0,0
3,10202,302905,2021-04-01,2021-04-01,3102459,8000,0,0,15:00,11:00,...,0,0,0,0,0,0,1,0,0,0
4,10202,302905,2021-04-01,2021-04-01,3102459,8000,0,0,15:00,11:00,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10134750,471723,382544,2021-04-01,2021-04-28,2317959,4320,0,0,11:00,10:00,...,0,0,0,1,0,1,0,0,0,0
10134751,471723,382544,2021-04-01,2021-04-29,2369744,4320,0,0,11:30,10:00,...,0,0,0,1,0,1,0,0,0,0
10134752,471723,382544,2021-04-01,2021-04-29,2317959,4320,0,0,11:00,10:00,...,0,0,0,1,0,1,0,0,0,0
10134753,471723,382544,2021-04-01,2021-04-30,2369744,4320,0,0,11:30,10:00,...,0,0,0,1,0,1,0,0,0,0
10134754,471723,382544,2021-04-01,2021-04-30,2317959,4320,0,0,11:00,10:00,...,0,0,0,1,0,1,0,0,0,0

In [33]:
df_s.describe()

,エリアコード,宿コード,プランコード,価格,朝食の有無,夕食の有無,プラン提供開始日,プラン提供終了日,残り部屋数,禁煙,...,和室,洋室,和洋室,シングル,セミダブル,ダブル,ツイン,トリプル,おまかせ,連泊
count,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,7.211988e+06,1.013476e+07,...,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07,1.013476e+07
mean,2.193072e+05,3.448760e+05,2.463410e+06,1.367996e+04,5.795061e-01,1.895710e-01,2.018311e+07,2.021252e+07,3.516817e+00,5.451261e-01,...,1.023191e-01,3.186786e-02,1.657475e-02,2.760798e-01,6.150233e-02,1.719963e-01,2.882683e-01,1.358474e-02,1.278028e-02,7.644980e-04
std,1.339435e+05,2.855594e+04,7.227341e+05,1.666366e+04,4.936383e-01,3.919616e-01,3.248203e+04,3.579543e+03,2.306878e+00,4.979595e-01,...,3.030675e-01,1.756482e-01,1.276716e-01,4.470568e-01,2.402494e-01,3.773772e-01,4.529566e-01,1.157592e-01,1.123252e-01,2.763899e-02
min,1.020200e+04,3.000000e+05,2.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,2.005113e+07,2.021040e+07,1.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.362050e+05,3.200080e+05,2.123940e+06,6.882000e+03,0.000000e+00,0.000000e+00,2.017080e+07,2.021072e+07,2.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.123020e+05,3.406780e+05,2.748913e+06,9.300000e+03,1.000000e+00,0.000000e+00,2.020032e+07,2.021093e+07,3.000000e+00,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,3.108020e+05,3.696560e+05,3.016482e+06,1.438000e+04,1.000000e+00,0.000000e+00,2.020121e+07,2.021123e+07,5.000000e+00,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,4.717230e+05,3.999800e+05,3.145646e+06,9.999990e+05,1.000000e+00,1.000000e+00,2.021043e+07,2.022043e+07,9.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [34]:
df_630738	 = df_s[df_s['プランコード'] == 630738]
print(df_630738)

        エリアコード    宿コード      データ取得日     チェックイン日  プランコード    価格  朝食の有無  夕食の有無  \
0        10202  300206  2021-04-01  2021-04-01  630738  3600      0      0
1        10202  300206  2021-04-01  2021-04-01  630738  3700      0      0
2        10202  300206  2021-04-01  2021-04-01  630738  4100      0      0
6206     10202  300206  2021-04-01  2021-04-02  630738  3600      0      0
6207     10202  300206  2021-04-01  2021-04-02  630738  3700      0      0
...        ...     ...         ...         ...     ...   ...    ...    ...
244730   10202  300206  2021-04-01  2021-04-29  630738  5100      0      0
244732   10202  300206  2021-04-01  2021-04-29  630738  5600      0      0
254133   10202  300206  2021-04-01  2021-04-30  630738  5600      0      0
254134   10202  300206  2021-04-01  2021-04-30  630738  6100      0      0
254136   10202  300206  2021-04-01  2021-04-30  630738  6600      0      0

       チェックイン時刻 チェックアウト時刻  ...  和室  洋室  和洋室  シングル  セミダブル  ダブル  ツイン  トリプル  \
0         15:00     11:00  ...   0   0    0     0      0    1    1     0
1         15:00     11:00  ...   0   0    0     0      0    1    0     0
2         15:00     11:00  ...   0   0    0     0      0    0    1     0
6206      15:00     11:00  ...   0   0    0     0      0    1    1     0
6207      15:00     11:00  ...   0   0    0     0      0    1    0     0
...         ...       ...  ...  ..  ..  ...   ...    ...  ...  ...   ...
244730    15:00     11:00  ...   0   0    0     0      0    1    0     0
244732    15:00     11:00  ...   0   0    0     0      0    0    1     0
254133    15:00     11:00  ...   0   0    0     0      0    1    1     0
254134    15:00     11:00  ...   0   0    0     0      0    1    0     0
254136    15:00     11:00  ...   0   0    0     0      0    0    1     0

        おまかせ  連泊
0          0   0
1          0   0
2          0   0
6206       0   0
6207       0   0
...      ...  ..
244730     0   0
244732     0   0
254133     0   0
254134     0   0
254136     0   0

[90 rows x 25 columns]

## サンプルデータをcsvファイルで保存

In [35]:
os.chdir("D:\じゃらん宿泊データ\sample_data")
df_s.to_csv(csv_file_name)

In [2]:
df = df.copy()
df.head()

,エリアコード,宿コード,データ取得日,チェックイン日,プランコード,価格,部屋情報,朝食の有無,夕食の有無,チェックイン時刻,チェックアウト時刻,プラン提供開始日,プラン提供終了日,イメージ画像URL,画像キャプション,残り部屋数
0,10202,300206,2021-04-01,2021-04-01,630738,3600,【1名利用】ダブルorツインルーム 2020年2月リニューアル済,0,0,15:00,11:00,20080916,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ダブルルーム ベッド幅140cm,NaN
1,10202,300206,2021-04-01,2021-04-01,630738,3700,禁煙ダブルルーム 2020年客室リニューアル完了（15～17平米）,0,0,15:00,11:00,20111118,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ダブルルーム ベッド幅140cm,NaN
2,10202,300206,2021-04-01,2021-04-01,630738,4100,禁煙ツインルーム 2020年客室リニューアル完了（18平米）,0,0,15:00,11:00,20080916,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ツインルーム ベッド幅120cm,6.0
3,10202,302905,2021-04-01,2021-04-01,3102459,8000,リニューアルフロア・ツイン/アーバン＜２３平米＞,0,0,15:00,11:00,20210220,20210531,https://www.jalan.net/jalan/images/pictM/Y5/Y3...,期間限定＆室数限定のお得なプラン♪,2.0
4,10202,302905,2021-04-01,2021-04-01,3102459,8000,スタンダードフロア・ツイン＜アーバンルーム＞２３平米,0,0,15:00,11:00,20210220,20210531,https://www.jalan.net/jalan/images/pictM/Y5/Y3...,期間限定＆室数限定のお得なプラン♪,2.0

In [3]:
df = df.iloc[:10000]
df

,エリアコード,宿コード,データ取得日,チェックイン日,プランコード,価格,部屋情報,朝食の有無,夕食の有無,チェックイン時刻,チェックアウト時刻,プラン提供開始日,プラン提供終了日,イメージ画像URL,画像キャプション,残り部屋数
0,10202,300206,2021-04-01,2021-04-01,630738,3600,【1名利用】ダブルorツインルーム 2020年2月リニューアル済,0,0,15:00,11:00,20080916,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ダブルルーム ベッド幅140cm,NaN
1,10202,300206,2021-04-01,2021-04-01,630738,3700,禁煙ダブルルーム 2020年客室リニューアル完了（15～17平米）,0,0,15:00,11:00,20111118,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ダブルルーム ベッド幅140cm,NaN
2,10202,300206,2021-04-01,2021-04-01,630738,4100,禁煙ツインルーム 2020年客室リニューアル完了（18平米）,0,0,15:00,11:00,20080916,20220228,https://www.jalan.net/jalan/images/pictM/Y6/Y3...,ツインルーム ベッド幅120cm,6.0
3,10202,302905,2021-04-01,2021-04-01,3102459,8000,リニューアルフロア・ツイン/アーバン＜２３平米＞,0,0,15:00,11:00,20210220,20210531,https://www.jalan.net/jalan/images/pictM/Y5/Y3...,期間限定＆室数限定のお得なプラン♪,2.0
4,10202,302905,2021-04-01,2021-04-01,3102459,8000,スタンダードフロア・ツイン＜アーバンルーム＞２３平米,0,0,15:00,11:00,20210220,20210531,https://www.jalan.net/jalan/images/pictM/Y5/Y3...,期間限定＆室数限定のお得なプラン♪,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10202,333592,2021-04-01,2021-04-02,3104821,19950,【最上階/道庁側】スーペリアツイン ２６平米 ＜禁煙＞,1,0,15:00,11:00,20210210,20210630,https://www.jalan.net/jalan/images/pictM/Y2/Y3...,期間限定のお得なプランはこちら！,3.0
9996,10202,333592,2021-04-01,2021-04-02,2968018,24700,【最上階/道庁側】スーペリアツイン ２６平米 ＜禁煙＞,1,0,15:00,11:00,20210201,20210427,https://www.jalan.net/jalan/images/pictM/Y2/Y3...,最上階スーペリアツイン(26平米/シングルベッド×2),3.0
9997,10202,333592,2021-04-01,2021-04-02,2967803,27500,【最上階/道庁側】スーペリアツイン ２６平米 ＜禁煙＞,1,0,15:00,11:00,20210201,20220228,https://www.jalan.net/jalan/images/pictM/Y2/Y3...,最上階スーペリアツイン(26平米/シングルベッド×2),3.0
9998,10202,333592,2021-04-01,2021-04-02,3104821,42750,【最上階/道庁側】プレミアムツイン ５６平米 ＜禁煙＞,1,0,15:00,11:00,20210210,20210630,https://www.jalan.net/jalan/images/pictM/Y2/Y3...,期間限定のお得なプランはこちら！,1.0
9999,10202,333592,2021-04-01,2021-04-02,2968018,54700,【最上階/道庁側】プレミアムツイン ５６平米 ＜禁煙＞,1,0,15:00,11:00,20210201,20210427,https://www.jalan.net/jalan/images/pictM/Y2/Y3...,最上階のプレミアムツイン、スーペリアダブル・ツインにご宿泊いただくプランです。,1.0

In [7]:
df_630738	 = df[df['プランコード'] == 630738]
print(df_630738)

        エリアコード    宿コード      データ取得日     チェックイン日  プランコード    価格  \
0        10202  300206  2021-04-01  2021-04-01  630738  3600
1        10202  300206  2021-04-01  2021-04-01  630738  3700
2        10202  300206  2021-04-01  2021-04-01  630738  4100
6206     10202  300206  2021-04-01  2021-04-02  630738  3600
6207     10202  300206  2021-04-01  2021-04-02  630738  3700
...        ...     ...         ...         ...     ...   ...
244730   10202  300206  2021-04-01  2021-04-29  630738  5100
244732   10202  300206  2021-04-01  2021-04-29  630738  5600
254133   10202  300206  2021-04-01  2021-04-30  630738  5600
254134   10202  300206  2021-04-01  2021-04-30  630738  6100
254136   10202  300206  2021-04-01  2021-04-30  630738  6600

                                      部屋情報  朝食の有無  夕食の有無 チェックイン時刻 チェックアウト時刻  \
0         【1名利用】ダブルorツインルーム　2020年2月リニューアル済      0      0    15:00     11:00
1       　禁煙ダブルルーム　2020年客室リニューアル完了（15～17平米）      0      0    15:00     11:00
2           禁煙ツインルーム　2020年客室リニューアル完了（18平米）      0      0    15:00     11:00
6206      【1名利用】ダブルorツインルーム　2020年2月リニューアル済      0      0    15:00     11:00
6207    　禁煙ダブルルーム　2020年客室リニューアル完了（15～17平米）      0      0    15:00     11:00
...                                    ...    ...    ...      ...       ...
244730  　禁煙ダブルルーム　2020年客室リニューアル完了（15～17平米）      0      0    15:00     11:00
244732      禁煙ツインルーム　2020年客室リニューアル完了（18平米）      0      0    15:00     11:00
254133    【1名利用】ダブルorツインルーム　2020年2月リニューアル済      0      0    15:00     11:00
254134  　禁煙ダブルルーム　2020年客室リニューアル完了（15～17平米）      0      0    15:00     11:00
254136      禁煙ツインルーム　2020年客室リニューアル完了（18平米）      0      0    15:00     11:00

        プラン提供開始日  プラン提供終了日                                          イメージ画像URL  \
0       20080916  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
1       20111118  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
2       20080916  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
6206    20080916  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
6207    20111118  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
...          ...       ...                                                ...
244730  20111118  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
244732  20080916  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
254133  20080916  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
254134  20111118  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...
254136  20080916  20220228  https://www.jalan.net/jalan/images/pictM/Y6/Y3...

                  画像キャプション  残り部屋数
0         ダブルルーム　ベッド幅140cm    NaN
1        ダブルルーム　　ベッド幅140cm    NaN
2       ツインルーム　　　ベッド幅120cm    6.0
6206      ダブルルーム　ベッド幅140cm    NaN
6207     ダブルルーム　　ベッド幅140cm    NaN
...                    ...    ...
244730   ダブルルーム　　ベッド幅140cm    NaN
244732  ツインルーム　　　ベッド幅120cm    7.0
254133    ダブルルーム　ベッド幅140cm    NaN
254134   ダブルルーム　　ベッド幅140cm    NaN
254136  ツインルーム　　　ベッド幅120cm    6.0

[90 rows x 16 columns]

In [13]:
kinnen = []
for text in df.iloc[:, 6]:
    kinnen.append("禁煙" in text)
kinnen
print(sum(kinnen))

6290

In [8]:
# 10000件のサンプルデータを保存する

os.chdir("D:\じゃらん宿泊データ\sample_data")
df.to_csv(csv_file_name)